SUBROUTINE dealloc_vectors
!
USE vector
USE mpi_inc
!
IMPLICIT NONE

IF (ALLOCATED (cho))DEALLOCATE (cho)
IF (ALLOCATED (nes))DEALLOCATE (nes)
IF (ALLOCATED (pres))DEALLOCATE (pres)
IF (ALLOCATED (rho))DEALLOCATE (rho)
IF (ALLOCATED (vx))DEALLOCATE (vx)
IF (ALLOCATED (vy))DEALLOCATE (vy)
IF (ALLOCATED (vz))DEALLOCATE (vz)
IF (ALLOCATED (ghalf))DEALLOCATE (ghalf)
IF (ALLOCATED (g))DEALLOCATE (g)
IF (ALLOCATED (c))DEALLOCATE (c)
IF (ALLOCATED (eint))DEALLOCATE (eint)
IF (ALLOCATED (etot))DEALLOCATE (etot)
IF (ALLOCATED (rhoold1d))DEALLOCATE (rhoold1d)
IF (ALLOCATED (vxold1d))DEALLOCATE (vxold1d)
IF (ALLOCATED (phi1))DEALLOCATE (phi1)
IF (ALLOCATED (phi0))DEALLOCATE (phi0)
IF (ALLOCATED (flt))DEALLOCATE (flt)
IF (ALLOCATED (nu))DEALLOCATE (nu)
IF (ALLOCATED (sk2))DEALLOCATE (sk2)
!
END SUBROUTINE dealloc_vectors
