SUBROUTINE RK4(Y,DYDX,N,X,H,YOUT)
      IMPLICIT NONE
      INTEGER :: N
      REAL*8  :: Y,DYDX,X,H,YOUT
      REAL*8  :: HH,H6,XH
      REAL*8  :: YT,DYT,DYM
      REAL*8  :: DERIVS

      HH=H*0.5
      H6=H/6.
      XH=X+HH

      YT=Y+HH*DYDX
      DYT=DERIVS(XH,YT)
      YT=Y+HH*DYT
      DYM=DERIVS(XH,YT)
      YT=Y+H*DYM
      DYM=DYT+DYM
      DYT=DERIVS(XH,YT)
      YOUT=Y+H6*(DYDX+DYT+2.*DYM)

END SUBROUTINE RK4
